---

- name: Check existence of matrix-swiclops service
  ansible.builtin.stat:
    path: "{{ matrix_systemd_path }}/matrix-swiclops.service"
  register: matrix_swiclops_service_stat

- name: Ensure matrix-swiclops is stopped
  ansible.builtin.systemd:
    name: matrix-swiclops
    state: stopped
    daemon_reload: true
  register: stopping_result
  when: "matrix_swiclops_service_stat.stat.exists"

- name: Ensure matrix-swiclops.service doesn't exist
  ansible.builtin.file:
    path: "{{ matrix_systemd_path }}/matrix-swiclops.service"
    state: absent
  when: "matrix_swiclops_service_stat.stat.exists"

- name: Ensure systemd reloaded after matrix-swiclops.service removal
  ansible.builtin.systemd:
    daemon_reload: true
  when: "matrix_swiclops_service_stat.stat.exists"

- name: Ensure Swiclops Docker image doesn't exist
  docker_image:
    name: "{{ matrix_swiclops_docker_image }}"
    state: absent
