---

- name: Check existence of matrix-swiclops service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-swiclops.service"
  register: matrix_swiclops_service_stat

- when: matrix_swiclops_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-swiclops is stopped
      ansible.builtin.service:
        name: matrix-swiclops
        state: stopped
        daemon_reload: true

    - name: Ensure matrix-swiclops.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-swiclops.service"
        state: absent
